# Generated by Django 3.0.4 on 2020-03-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('remove_shop', 'Can remove shop'),), 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
    ]
