# Generated by Django 3.0.4 on 2020-03-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20200311_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('update_shop_details', 'Update shop details'),), 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
    ]
