# Generated by Django 3.0.4 on 2020-03-11 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20200311_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
    ]
